/**
 * vsCRT.showHelp — opens the consolidated Help webview. Content comes
 * from `media/help-content.json`, which is regenerated by
 * `scripts/generate-help-content.mjs` at build time so it stays in
 * sync with package.json (commands, settings, keybindings).
 */

import * as vscode from "vscode";
import { generateNonce } from "../treeView/webviewNonce";
import type { CommandDeps } from "./types";

export function registerHelpPanelCommand(
  deps: CommandDeps,
): vscode.Disposable[] {
  const { context } = deps;
  return [
    vscode.commands.registerCommand("vsCRT.showHelp", () => {
    const panel = vscode.window.createWebviewPanel(
      "vscrtHelp",
      "vsCRT Help",
      vscode.ViewColumn.Active,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [vscode.Uri.joinPath(context.extensionUri, "media")],
      },
    );

    const mediaRoot = vscode.Uri.joinPath(context.extensionUri, "media");
    const codiconsCssUri = panel.webview.asWebviewUri(
      vscode.Uri.joinPath(
        context.extensionUri,
        "node_modules",
        "@vscode",
        "codicons",
        "dist",
        "codicon.css",
      ),
    );
    const cssUri = panel.webview.asWebviewUri(
      vscode.Uri.joinPath(mediaRoot, "help.css"),
    );
    const jsUri = panel.webview.asWebviewUri(
      vscode.Uri.joinPath(mediaRoot, "help.js"),
    );
    const contentUri = vscode.Uri.joinPath(mediaRoot, "help-content.json");
    const nonce = generateNonce();
    const csp = [
      `default-src 'none'`,
      `img-src ${panel.webview.cspSource} https: data:`,
      `style-src ${panel.webview.cspSource} 'unsafe-inline'`,
      `font-src ${panel.webview.cspSource}`,
      `script-src 'nonce-${nonce}'`,
    ].join("; ");

    vscode.workspace.fs.readFile(
      vscode.Uri.joinPath(mediaRoot, "help.html"),
    ).then(async (htmlBytes) => {
      let contentJson = "{}";
      try {
        const bytes = await vscode.workspace.fs.readFile(contentUri);
        contentJson = Buffer.from(bytes).toString("utf-8");
      } catch {
        // Generator hasn't run; panel still opens with empty content +
        // a note in the body.
      }
      const html = Buffer.from(htmlBytes).toString("utf-8")
        .replace(/\$\{csp\}/g, csp)
        .replace(/\$\{codiconsCssUri\}/g, codiconsCssUri.toString())
        .replace(/\$\{cssUri\}/g, cssUri.toString())
        .replace(/\$\{jsUri\}/g, jsUri.toString())
        .replace(/\$\{nonce\}/g, nonce)
        .replace(/\$\{contentJson\}/g, contentJson);
      panel.webview.html = html;
    });

    panel.webview.onDidReceiveMessage((msg: unknown) => {
      if (!msg || typeof msg !== "object") {return;}
      const m = msg as { type?: string; id?: string };
      if (m.type === "runCommand" && typeof m.id === "string") {
        void vscode.commands.executeCommand(m.id);
      } else if (m.type === "openSetting" && typeof m.id === "string") {
        void vscode.commands.executeCommand(
          "workbench.action.openSettings",
          m.id,
        );
      }
    });
  }),
  ];
}
